//Vector declare & push_back & print...
#include<bits/stdc++.h>
using namespace std;
int main(){
   vector<int>v;//Vector declare...
   //Value push_back...
   v.push_back(10);
   v.push_back(50);
   v.push_back(40);
   v.push_back(30);
   cout<<v[1]<<endl;//print Vector...
    return 0;
}
